# Generated by Django 3.0 on 2019-12-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkLot',
            fields=[
                ('park_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_address', models.TextField(default='')),
                ('rent_date', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('description_tag', models.TextField(default='')),
                ('detail_word', models.TextField(default='')),
                ('rent_state', models.IntegerField(default=0)),
                ('remark', models.TextField(default='')),
                ('longitude', models.FloatField(db_index=True, default=0)),
                ('latitude', models.FloatField(db_index=True, default=0)),
                ('renter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionPic',
            fields=[
                ('pic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='park_pic')),
                ('park_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.ParkLot')),
            ],
        ),
    ]
