# Generated by Django 3.0 on 2019-12-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parklot',
            name='description_tag',
        ),
    ]
