# Generated by Django 3.0 on 2019-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('icon', models.ImageField(default='media/icon/timg.jpeg', upload_to='icon')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('sex', models.IntegerField(default=0)),
                ('bankcard', models.CharField(default='', max_length=30)),
                ('ID', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
