# Generated by Django 3.0 on 2019-12-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_lot', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('book_time_start', models.DateTimeField()),
                ('book_time_end', models.DateTimeField()),
                ('price', models.FloatField()),
                ('pay_state', models.IntegerField()),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessor', to='user.User')),
                ('park_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.ParkLot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='user.User')),
            ],
        ),
    ]
