# Generated by Django 3.0 on 2019-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_state',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
